# version: '3.9'
# services:
#   mongo_db:
#     container_name: mongo_db
#     image: mongo:latest
#     # restart: always
#     volumes:
#       - mongo_db:/data/db

#   randomid321_nodetestapp:
#     build: .
#     ports:
#       - 2022:8080
#     environment:
#     #   PORT: 8080
#       MONGODB_URI: mongodb://mongo_db:27017
#     depends_on:
#       - mongo_db

# volumes:
#   mongo_db: {}
version: '3'
services:
  randomid321_nodetestapp:
    image: "randomid321/nodetestapp"
    build: .
    command: "node app.js"
    ports:
      - "2022:8080"
    depends_on:
      - "mongo_db"
  mongo_db:
    image: "mongo:latest"
    ports:
      - "27017:27017"